version: "3.9"
services: 
  web:
    build: .
    ports:
     ["80:3000"]
    volumes: 
      - .:/src
    environment:
      -NODE_ENV: development 
  mongo:
    image: "mongo"
    ports:
      ["27017:27017"]